### ISSUE TITLE
Problems running on atmega328p

### ISSUE THREAD

**Issue by joaoantoniocardoso** [dergraaf/avr-can-lib#12]
Hi,

I'm trying to run this library with an **atmega328p**, but it isn't working - I think it is something wrong with the **SPI** because *SCK*, *MOSI* and *MISO* hasn't any signal running the *can_init* function.

I'm not very familiarized using third party library, even **SPI**, so I will describe how I get here:

- Before I build the library, I changed *src/makefile* @ line 44 to `MCU = atmega328p`
- Then I build with `make lib` and copied the *libcan.a* to *demo/libcan.a*
- I changed the *demo/makefile* @ line 44 to `MCU = atmega328p`, then uploaded with `avrdude -c arduino -P /dev/ttyACM0 -p m328p -D -U flash:w:can_testprogram.elf` but nothing happens on *SCK*, *MOSI* and *MISO* pins.

The hardware so far is an *Arduino UNO R3* board with all board pins opened and SPI on osciloscope.
I don't think it has something to do with, but for state, I'm running an updated archlinux.

So what am I doing wrong?
Thanks

**Comment by uescher** [comment]
@dergraaf 
please close this request. thx
