### ISSUE TITLE
Wrong defines in can_private.h line80 ... 128

### ISSUE THREAD

**Issue by dnrelectronica** [dergraaf/avr-can-lib#18]
Hi guys, 

I got stuck on the code part in can_private.h. THere are macro's for the three types of controllers which are supported, namely: MCP2515, At90CAN, and SJA1000. I think the defines are reversed, but i am not sure. The defines look like this:

#define mcp2515_init(...)		can_init(__VA_ARGS__)

But i think it should be like this:

#define can_init(...)		         mcp2515_init(__VA_ARGS__)

Because you call in your main the function can_init() and dependent on which controller/device you use it will call the appriopriate function. I use the AT90CAN, so when i call can_init() it should call the init driver function for the at90can like: at90can_init(). 

Do you agree with me? Or am i wrong?

Kind Regards, 
Corné Doggen.

**Comment by dergraaf** [comment]
Hi,

the defines are correct the way they are. What they are doing is to rename the functions in the library. 
With the current implementation the functions in the object files are called actually called `can_...`.

The way you are proposing would also work, that way you would rename the functions in the application code. Both are valid possibilities.

Cheers, Fabian

**Comment by dnrelectronica** [comment]
I understand , therefore the function at90can_init doesnt exist anymore in application code since iT is renamed can_init().

Thanks !

Kind regards ,
Corne

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Fabian Greif <notifications@github.com>
Verzonden: woensdag, juni 19, 2019 18:41
Aan: dergraaf/avr-can-lib
CC: Corné || D&R Electronica; Author
Onderwerp: Re: [dergraaf/avr-can-lib] Wrong defines in can_private.h line80 ... 128 (#18)


Hi,

the defines are correct the way they are. What they are doing is to rename the functions in the library.
With the current implementation the functions in the object files are called actually called can_....

The way you are proposing would also work, that way you would rename the functions in the application code. Both are valid possibilities.

Cheers, Fabian
