### ISSUE TITLE
AT90CAN64 keeps sending message over and over again... 

### ISSUE THREAD

**Issue by dnrelectronica** [dergraaf/avr-can-lib#19]
Hi all, 

I have an issue with the AT90CAN64 controller in combination with this library. If i run the example program from the webpage the code seems to send only ONCE the message since it is before the while() loop. If i check the TXD-CAN pin (PD5) of the Atmel it show continues activity.. It looks like the atmel keeps sending this message over and over again because it receives a NACK everytime? I have no other CAN nodes connected to the CAN bus, only the Atmel with a 120 Ohm resister for termination. What could be the problem? I want the library to send only once the message and not over and over again until somebody (other node) acknolegde this message. Can i turn this off somewhere? 

I think it is the application who is responsible for resending the message if something went wrong, but now it automatically resends the message very fast behind each other. In this way the CAN bus gets lots of data to handle.. busy buss.. :(. 

Maybe somebody can help me out what i am doing wrong , or think the wrong way. Maybe it is required to always have 2 nodes on the network otherwise you get this behaviour. i don't know. If i connect another node (LAWICEL CANUSB cable) the message is sent only once. It seems the CANUSB cable node acknowledge the message?? can you confirm this? 

Kind Regards, 

Corné Doggen.

**Comment by dergraaf** [comment]
> It looks like the atmel keeps sending this message over and over again because it receives a NACK everytime?

That is exactly what is happening.

> I have no other CAN nodes connected to the CAN bus, only the Atmel with a 120 Ohm resister for termination.

As you already discovered, that is the problem. You always need at least two CAN nodes.

> I think it is the application who is responsible for resending the message if something went wrong, but now it automatically resends the message very fast behind each other. In this way the CAN bus gets lots of data to handle.. busy buss.. :(.

The resend until an acknowledge is received is a feature of the CAN bus controller. There won't be any additional data to be handled if any node acknowledges the first CAN controller.

> Maybe it is required to always have 2 nodes on the network otherwise you get this behaviour.

This is the case.

**Comment by dnrelectronica** [comment]
Hi ,

Thank You so much for the confirmation! I have another question right now. If i place the can_send_message() inside the while loop (with a 100ms delay) i expect a message every 100ms , but iT sends iT only once. Any Idea?

For example a keep Alive message need to be sent over the network every Lets say 100ms. The message is exactly the same every time. Can this be the problem? The lib recognize the message and think iT is the same message as before so ignores iT?
