### ISSUE TITLE
Common MCP2515 + TJA1050 Module Support

### ISSUE THREAD

**Issue by lberezy** [dergraaf/avr-can-lib#8]
Does this library support the commonly found [MCP2515 + TJA1050 CAN module](http://www.aliexpress.com/store/product/MCP2515-CAN-Bus-Module-TJA1050-receiver-SPI-For-51-MCU-ARM-controller-Free-shipping/627093_2024232763.html) that is found all over eBay and the likes?

As a follow up question, what frequency crystal is the MC2515 support configured for? I've got a few of those modules mentioned above that come with 8 MHz crystals.

**Comment by uescher** [comment]
It is supported.
The estimated frequency is 16 MHz.
Either you select 250kbps instead of 125kbps or you should change this file:
https://github.com/dergraaf/avr-can-lib/blob/master/src/mcp2515.c#L128-L169
There you can change the constants.

**Comment by uescher** [comment]
@dergraaf 
please close this request. thx
